setting cmems_username and cmems_password conditionally
dcs4cop/xcube-cmems pull request #23
Opened 2023-03-13 10:23 UTC by TejasMorbagal

2023-03-13 11:34 UTC, TonioF requested changes
The functionality itself works, but in the notebook the parameters are set neither as environment variables nor as store parameters. Ideally you should explain both there.
Also, please make sure that the first cell in a notebook is a heading and consider adding more descriptions between the headings.

2023-03-13 11:34 UTC, TonioF commented on xcube_cmems/cmems.py
>                              'provided as store params')
If they are store params, they must be written in small caps, so you should better write their full names here.

2023-03-14 15:55 UTC, pont-us approved these changes
Looks good, tests pass, notebook runs. Approved!

2023-03-16 09:42 UTC, TonioF approved these changes

2023-03-16 11:21 UTC, merged